version: "3.8"
services:
  h_api_database:
    image: postgres:latest
    container_name: h_api_database
    environment:
      POSTGRES_DB: happy
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - './docker/postgres/data:/var/lib/postgresql/data'

  h_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: h_api
    ports:
      - 8000:8000
    depends_on:
      - h_api_database
    links:
      - h_api_database
    volumes:
      - ./:/app
    restart: always    
